name: RAI Health Check Pipeline (Every 8h)

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  run-health-check:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Full Evaluation Pipeline
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
        AGENT_ID: ${{ secrets.AGENT_ID }}
        DATASET_IDS: ${{ secrets.DATASET_IDS }}
        METRIC_IDS: ${{ secrets.METRIC_IDS }}
      run: python run_full_evaluation_pipeline.py
